spring:
  config:
    activate:
      on-profile:
        - dev

  application:
    name: job-service

  datasource:
    url: jdbc:postgresql://localhost:5434/job-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:database/migration

jwt:
  secret: ${JWT_SECRET}
  accessExpiration: 900000
  refreshExpiration: 604800000

springdoc:
  swagger-ui:
    path: /docs

server:
  port: 8082